loadbalancer:
  image: dockercloud/haproxy
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - 80:80
  links:
    - webclient

webclient:
  build: .
  restart: always
  environment:
    - NODE_ENV=production
    - VIRTUAL_HOST=lupi.online

newrelic:
  image: uzyexe/newrelic
  restart: "on-failure"
  privileged: true
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/dev:/dev"
    - "/sys:/sys"
  environment:
    - NEW_RELIC_LICENSE_KEY
  pid: host
  net: host
